
// Re-export core state types from the new centralized state.ts file
export * from './state';

// Types that are not core state or are more general utility types remain here,
// or can be moved to other more specific type files if needed.

export type PaletteGenieColor = {
  hue: number;
  saturation: number;
  brightness: number;
};

export type ProceduralAsset = {
  textureDataUri?: string;
  meshDataUri?: string;
};

export type Cue = {
  time: number;
  action: 'change_scene' | 'set_setting';
  payload: {
    sceneId?: string;
    // Ensure Settings is available here, it will be via `export * from './state'`
    settingKey?: keyof import('./state').Settings;
    settingValue?: any;
  };
};

export type RehearsalLogEntry = {
  id?: number; // Optional: auto-generated by IndexedDB
  timestamp: number;
  event: string; // e.g., 'scene_change', 'setting_update', 'ai_overlay_generated'
  details: Record<string, any>; // e.g., { sceneId: '...', reason: '...' }
};
